version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cleverbot-free
    versions:
    - 1.1.1
    - 1.1.4
    - 1.1.5
  - dependency-name: eslint
    versions:
    - 7.24.0
