// Description:
//   Event system related utilities
//
// Commands:
//   hubot fake event <event> - Triggers the <event> event for debugging reasons
//
// Events:
//   debug - {user: <user object to send message to>}

// Generated by CoffeeScript 1.6.3
(function() {
	let util;

	util = require("util");

	module.exports = function(robot) {
		robot.respond(/FAKE EVENT (.*)/i, (msg) => {
			msg.send(`fake event '${msg.match[1]}' triggered`);
			return robot.emit(msg.match[1], {
				user: msg.message.user
			});
		});
		return robot.on("debug", (event) => {
			return robot.send(event.user, util.inspect(event));
		});
	};

}).call(this);
