name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to GCR Registry
        if: github.ref == 'refs/heads/master'
        run: echo ${{ secrets.GCR_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io/${{ github.repository }}
      -
        name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: github.ref == 'refs/heads/master'
          tags: ghcr.io/${{ github.repository }}:${{steps.vars.outputs.tag}}
